BoxLayout:
    orientation: 'vertical'

    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_miles
            text: '34'
            font_size: 48

        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 0.25
            Button:
                text: 'Up'
            Button:
                text: 'Down'


    Label:
        id: output_label
        font_size: 48
        text: ''
        color: (1, 1, 0, 1)